name: skype
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.9
  firebase_auth: '0.11.1+7'
  google_sign_in: 4.0.2
  shimmer: 1.0.1
  new_gradient_app_bar: ^0.2.0
  emoji_picker: ^0.1.0
  image_picker: ^0.7.5
  path_provider: ^1.6.0
  firebase_storage: ^3.1.1
  provider: ^4.0.3
  cached_network_image: ^2.0.0
  agora_rtc_engine: ^1.0.8
  permission_handler: 3.0.0
  sqflite: ^1.3.0+1
  hive: 1.4.1+1
  intl: 0.16.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
